
default: &default
  adapter: postgresql

development:
  <<: *default
  database: amplitude_db_development

test:
  <<: *default
  database: amplitude_db_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
